### ISSUE TITLE
Downloaded the exe and get a Defender warning on launch

### ISSUE THREAD

**Issue by pcause** [voletro/wsa-toolbox#9]
Just downloaded the exe from releases and get a warning from defender that this may be malware

**Comment by voletro** [comment]
This happens because my app is not signed by Microsoft. Signing an app is expensive so smaller developers cannot afford to get their applications signed. The exe is perfectly safe and can be checked for viruses [here](https://www.virustotal.com/gui/file/0c107ecee06b546faedfd65e1cbac1022d902a96aed2363fa4169f84b416ee61) on virustotal. 
You can always look at the source code of this project as well as build it yourself with the instructions in the readme if you would like to do that.
